apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/anexprod/final_python.git"
    targetRevision: HEAD
    path: "./devops_soft/step-final/.github\workflows"  # Путь к папке, где находятся манифесты Kubernetes
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
